#
#Wed Jun 17 15:24:45 GMT-05:00 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[start-maximized, incognito, start-maximized, incognito, remote-allow-origins\=*], extensions\=[]}
